= Solution Pattern: Cluster as a Service
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

This solution pattern brings an architectural solution demonstrating how easily we can create multiple Kuberenetes clusters in AWS cloud directly from the Github code repository using GitHub Actions. In this pattern, we will be deploying multiple Managed Openshift clusters using Terraform in different AWS accounts using a deployment pipeline.

*Contributors*: _https://github.com/gmidha1[Gaurav Midha (Red Hat)^]_

[#caas]
== What is Cluster as a service

Cluster as a service provides an easy way to define clusters using code and allows engineers to create these clusters. The main goal of ClaaS is to build a scalable, efficient and easy-to-use system to provide virtual clusters as services to an enterprise’s trusted users.

Its features are following:

- Deploy fully provisioned clusters: Once a cluster is ready, users can start using the clusters immediately. It reduces cost and increases the speed of deployments.
- Code-driven: All configurations of the cluster are stored in a git repo. It reduces error and eliminates configuration drifts.
- Automated deployment pipeline: Clusters are created using automated deployment pipelines. It improves infrastructure consistency.
- Manage multiple clusters across multi regions easily: Clusters can be deployed and managed in Multi Region or Multiple AWS accounts.

include::01-pattern.adoc[]

== Explore more solution patterns
include::https://raw.githubusercontent.com/redhat-solution-patterns/redhat-solution-patterns.github.io/master/documentation/modules/ROOT/pages/solution-pattern-list.adoc[]
